In [1]:
import numpy as np

In [2]:
arr=np.zeros(10)

In [3]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr1=np.ones(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr2=np.full(10,5)
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
arr3=np.arange(10,51)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
arr4=np.arange(10,51,2)
arr4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
arr5=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr6=np.identity(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr7=np.linspace(0,1,20)
arr7

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [15]:
arr8=np.arange(1,26).reshape(5,5)
arr8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr8[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [23]:
arr8[3,4]

20

In [24]:
arr8[0:3,1]

array([ 2,  7, 12])

In [25]:
arr8[4:,0:5]

array([[21, 22, 23, 24, 25]])

In [26]:
arr8[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
mat=arr8

In [29]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
mat.sum()

325

In [31]:
mat.std()

7.211102550927978

In [34]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
mat1=mat[:, 0]
mat1
a=mat1.sum()
a=np.array([a])
a

array([55])

In [84]:
mat2=mat[:, 1]
mat2
b=mat2.sum()
b=np.array([b])
b

array([60])

In [85]:
mat3=mat[:, 2]
mat3
c=mat3.sum()
c=np.array([c])
c

array([65])

In [86]:
mat4=mat[:, 3]
mat4
d=mat4.sum()
d=np.array([d])
d

array([70])

In [87]:
mat5=mat[:, 4]
mat
e=mat5.sum()
e=np.array([e])
e

array([75])

In [89]:
np.concatenate((a,b,c,d,e))

array([55, 60, 65, 70, 75])